_: {
  imports = [
    # ./none-ls.nix
    ./autopairs.nix
    ./bufferline.nix
    ./catppuccin.nix
    ./comment.nix
    ./conform.nix
    ./clangd-extensions.nix
    ./cmp.nix
    ./diffview.nix
    ./flash.nix
    ./git-conflict.nix
    ./gitsigns.nix
    ./harpoon.nix
    ./illuminate.nix
    ./lightbulb.nix
    ./lualine.nix
    ./lean.nix
    ./lsp.nix
    ./mini-bufremove.nix
    ./navic.nix
    ./nix.nix
    ./noice.nix
    ./notify.nix
    ./precognition.nix
    ./spectre.nix
    ./refactoring.nix
    ./telescope.nix
    ./todo-comments.nix
    ./toggleterm.nix
    ./treesitter.nix
    ./trouble.nix
    ./which-key.nix
    ./undotree.nix
    ./yazi.nix
    ./vimtex.nix
  ];
}
